const People = [
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 1,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 2,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 3,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 4,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 5,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 6,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 7,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 8,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 9,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 10,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 11,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 12,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 13,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 14,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 15,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 16,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 17,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 18,
        connected: false,
    },{
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 19,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 20,
        connected: false,
    },{
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 21,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://image.freepik.com/free-photo/food-background-food-concept-with-various-tasty-fresh-ingredients-for-cooking-italian-food-ingredients-view-from-above-with-copy-space_1220-1491.jpg',
        id: 22,
        connected: false,
    }

];

export default People;