const People = [
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 1,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://i.kinja-img.com/gawker-media/image/upload/s--Sa8eI0xi--/c_scale,f_auto,fl_progressive,q_80,w_800/18ixcbxyge3svjpg.jpg',
        id: 2,
        connected: true,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 3,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://i.kinja-img.com/gawker-media/image/upload/s--Sa8eI0xi--/c_scale,f_auto,fl_progressive,q_80,w_800/18ixcbxyge3svjpg.jpg',
        id: 4,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 5,
        connected: true,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://i.kinja-img.com/gawker-media/image/upload/s--Sa8eI0xi--/c_scale,f_auto,fl_progressive,q_80,w_800/18ixcbxyge3svjpg.jpg',
        id: 6,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 7,
        connected: true,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://i.kinja-img.com/gawker-media/image/upload/s--Sa8eI0xi--/c_scale,f_auto,fl_progressive,q_80,w_800/18ixcbxyge3svjpg.jpg',
        id: 8,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 9,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://i.kinja-img.com/gawker-media/image/upload/s--Sa8eI0xi--/c_scale,f_auto,fl_progressive,q_80,w_800/18ixcbxyge3svjpg.jpg',
        id: 10,
        connected: true,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 11,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://i.kinja-img.com/gawker-media/image/upload/s--Sa8eI0xi--/c_scale,f_auto,fl_progressive,q_80,w_800/18ixcbxyge3svjpg.jpg',
        id: 12,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 13,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://i.kinja-img.com/gawker-media/image/upload/s--Sa8eI0xi--/c_scale,f_auto,fl_progressive,q_80,w_800/18ixcbxyge3svjpg.jpg',
        id: 14,
        connected: true,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 15,
        connected: false,
    },
    {
        username: "Kitty Kat",
        occupation: 'Unemployed',
        imageUrl: 'https://i.kinja-img.com/gawker-media/image/upload/s--Sa8eI0xi--/c_scale,f_auto,fl_progressive,q_80,w_800/18ixcbxyge3svjpg.jpg',
        id: 16,
        connected: false,
    },
    {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 17,
        connected: false,
    },
        {
        username: "Doggy Dog",
        occupation: 'People Walker',
        imageUrl: 'http://photos.jibble.org/Wildlife%20and%20Pets/Other%20Pets/Nelson_The_Dog_With_A_Stick_IMG_0596.jpg',
        id: 18,
        connected: true,
    }
];

export default People;